name: todo_algoriza
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  adaptive_theme: ^3.1.1
  calender_picker: ^1.0.7
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.2
  date_picker_timeline: ^1.2.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_local_notifications: ^9.7.0
  flutter_native_timezone: ^2.0.0
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.0
  fluttertoast: ^8.0.9
  intl: ^0.17.0
  nepali_utils: ^3.0.3
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  sqflite: ^2.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.3+1
  flutter_test:
    sdk: flutter
flutter_native_splash:
  color: "#ffffff"

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/onboarding_logo1.png
    - assets/images/onboarding_logo2.png
    - assets/images/onboarding_logo3.png
    - assets/images/onboarding_logo4.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Jannah
      fonts:
        - asset: assets/fonts/jannah.ttf
          weight: 700
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
